sudo: required
dist: trusty
language: python
python:
    - 2.7
#    - 3.4

script:
    - python setup.py install 
    - py.test test

notifications:
    email:
        on_success: never
        on_failure: never
